import InfiniteZero.ParityOperatorDecomposition

/-!
# Global one-mode and two-mode eigenspaces from parity certificates

Projection preserves the true eigen-equation. Distinct sector ground energies
leave only the lower mode at the global bottom, while coincident energies give
exactly the span of the two parity modes. Sector complement bounds also yield
an actual positive gap above the global bottom, including at a crossing.
-/

noncomputable section
namespace InfiniteZero

variable (A : L2Space →ₗ.[ℂ] L2Space)
variable (hP : ∀ even : Bool, ∀ q ∈ A.graph,
  ((l2ParitySector even).starProjection q.1,
    (l2ParitySector even).starProjection q.2) ∈ A.graph)

theorem parityDomainProjection_eigenvector (even : Bool) {E : ℝ} (u : A.domain)
    (hu : A u = (E : ℂ) • (u : L2Space)) :
    A (parityDomainProjection A hP even u) =
      (E : ℂ) • (parityDomainProjection A hP even u : L2Space) := by
  rw [parityDomainProjection_apply, hu, map_smul, parityDomainProjection_coe]

namespace ParityGroundCertificate

variable {A} {even : Bool} {E F : ℝ}
include hP

/-- With distinct sector bottoms, every global eigenvector at the lower
energy lies in the line generated by that sector ground vector. -/
theorem global_eigenvector_eq_smul_of_lt
    (c : ParityGroundCertificate A even E) (d : ParityGroundCertificate A (!even) F)
    (hEF : E < F) (u : A.domain) (hu : A u = (E : ℂ) • (u : L2Space)) :
    ∃ a : ℂ, u = a • c.vector := by
  let uE := parityDomainProjection A hP even u
  let uF := parityDomainProjection A hP (!even) u
  have hFEig : A uF = (E : ℂ) • (uF : L2Space) :=
    parityDomainProjection_eigenvector A hP (!even) u hu
  have hFbound := d.lower_bound uF (parityDomainProjection_parity A hP (!even) u)
  rw [re_inner_eq_of_operator_eigenvector A E uF hFEig] at hFbound
  have hFzero : uF = 0 := by
    apply Subtype.ext
    apply norm_eq_zero.mp
    apply sq_eq_zero_iff.mp
    have hs : ‖(uF : L2Space)‖ ^ 2 ≤ 0 :=
      (mul_le_mul_iff_right₀ (sub_pos.mpr hEF)).mp (by nlinarith only [hFbound])
    exact le_antisymm hs (sq_nonneg _)
  obtain ⟨a, ha⟩ := c.eigenvector_eq_smul uE
    (parityDomainProjection_parity A hP even u)
    (parityDomainProjection_eigenvector A hP even u hu)
  have hdecomp : uE + uF = u := parityDomainProjection_add_not A hP even u
  exact ⟨a, by simpa only [hFzero, add_zero, ha] using hdecomp.symm⟩

theorem global_eigenspace_eq_span_of_lt
    (c : ParityGroundCertificate A even E) (d : ParityGroundCertificate A (!even) F)
    (hEF : E < F) :
    operatorEigenspace A E = Submodule.span ℂ {(c.vector : L2Space)} := by
  apply le_antisymm
  · intro u hu
    obtain ⟨x, hx, hAx⟩ := A.mem_graph_iff.mp ((mem_operatorEigenspace A E u).mp hu)
    have heig : A x = (E : ℂ) • (x : L2Space) := by simpa only [hx] using hAx
    obtain ⟨a, ha⟩ := c.global_eigenvector_eq_smul_of_lt hP d hEF x heig
    exact Submodule.mem_span_singleton.mpr
      ⟨a, (hx.symm.trans (congrArg Subtype.val ha)).symm⟩
  · rw [Submodule.span_le, Set.singleton_subset_iff]
    exact c.vector_mem_parityEigenspace.1

/-- At a crossing, every global eigenvector is the sum of the two genuine
sector eigenvectors, with complex coefficients. -/
theorem global_eigenvector_eq_add_smul
    (c : ParityGroundCertificate A even E) (d : ParityGroundCertificate A (!even) E)
    (u : A.domain) (hu : A u = (E : ℂ) • (u : L2Space)) :
    ∃ a b : ℂ, u = a • c.vector + b • d.vector := by
  obtain ⟨a, ha⟩ := c.eigenvector_eq_smul (parityDomainProjection A hP even u)
    (parityDomainProjection_parity A hP even u)
    (parityDomainProjection_eigenvector A hP even u hu)
  obtain ⟨b, hb⟩ := d.eigenvector_eq_smul (parityDomainProjection A hP (!even) u)
    (parityDomainProjection_parity A hP (!even) u)
    (parityDomainProjection_eigenvector A hP (!even) u hu)
  exact ⟨a, b, by
    rw [← ha, ← hb]
    exact (parityDomainProjection_add_not A hP even u).symm⟩

theorem global_eigenspace_eq_span_pair
    (c : ParityGroundCertificate A even E) (d : ParityGroundCertificate A (!even) E) :
    operatorEigenspace A E =
      Submodule.span ℂ ({(c.vector : L2Space), (d.vector : L2Space)} : Set L2Space) := by
  apply le_antisymm
  · intro u hu
    obtain ⟨x, hx, hAx⟩ := A.mem_graph_iff.mp ((mem_operatorEigenspace A E u).mp hu)
    have heig : A x = (E : ℂ) • (x : L2Space) := by simpa only [hx] using hAx
    obtain ⟨a, b, hab⟩ := c.global_eigenvector_eq_add_smul hP d x heig
    exact Submodule.mem_span_pair.mpr
      ⟨a, b, (hx.symm.trans (congrArg Subtype.val hab)).symm⟩
  · apply Submodule.span_le.mpr
    intro u hu
    rcases Set.mem_insert_iff.mp hu with rfl | hu
    · exact c.vector_mem_parityEigenspace.1
    · have hdu : u = (d.vector : L2Space) := Set.mem_singleton_iff.mp hu
      rw [hdu]
      exact d.vector_mem_parityEigenspace.1

/-- The common complement of the two modes retains both sector floors. -/
theorem global_twoMode_complement_lower_bound
    (c : ParityGroundCertificate A even E) (d : ParityGroundCertificate A (!even) F)
    (u : A.domain)
    (huc : inner ℂ (c.vector : L2Space) (u : L2Space) = 0)
    (hud : inner ℂ (d.vector : L2Space) (u : L2Space) = 0) :
    min (E + c.gap) (F + d.gap) * ‖(u : L2Space)‖ ^ 2 ≤
      (inner ℂ (u : L2Space) (A u)).re := by
  have hc := c.gap_bound (parityDomainProjection A hP even u)
    (parityDomainProjection_parity A hP even u)
    (by rw [inner_parityDomainProjection_eq A hP c.parity u, huc])
  have hd := d.gap_bound (parityDomainProjection A hP (!even) u)
    (parityDomainProjection_parity A hP (!even) u)
    (by rw [inner_parityDomainProjection_eq A hP d.parity u, hud])
  have hmE := mul_le_mul_of_nonneg_right (min_le_left (E + c.gap) (F + d.gap))
    (sq_nonneg ‖(parityDomainProjection A hP even u : L2Space)‖)
  have hmF := mul_le_mul_of_nonneg_right (min_le_right (E + c.gap) (F + d.gap))
    (sq_nonneg ‖(parityDomainProjection A hP (!even) u : L2Space)‖)
  rw [norm_sq_eq_parityDomainProjection_add A hP even u,
    inner_operator_eq_parityDomainProjection_add A hP even u, Complex.add_re]
  nlinarith only [hc, hd, hmE, hmF]

/-- The complement of a single mode has the minimum of its sector gap floor
and the opposite sector bottom as a global lower bound. -/
theorem global_complement_lower_bound_min
    (c : ParityGroundCertificate A even E) (d : ParityGroundCertificate A (!even) F)
    (u : A.domain) (hu : inner ℂ (c.vector : L2Space) (u : L2Space) = 0) :
    min (E + c.gap) F * ‖(u : L2Space)‖ ^ 2 ≤
      (inner ℂ (u : L2Space) (A u)).re := by
  have hc := c.gap_bound (parityDomainProjection A hP even u)
    (parityDomainProjection_parity A hP even u)
    (by rw [inner_parityDomainProjection_eq A hP c.parity u, hu])
  have hd := d.lower_bound (parityDomainProjection A hP (!even) u)
    (parityDomainProjection_parity A hP (!even) u)
  have hmE := mul_le_mul_of_nonneg_right (min_le_left (E + c.gap) F)
    (sq_nonneg ‖(parityDomainProjection A hP even u : L2Space)‖)
  have hmF := mul_le_mul_of_nonneg_right (min_le_right (E + c.gap) F)
    (sq_nonneg ‖(parityDomainProjection A hP (!even) u : L2Space)‖)
  rw [norm_sq_eq_parityDomainProjection_add A hP even u,
    inner_operator_eq_parityDomainProjection_add A hP even u, Complex.add_re]
  nlinarith only [hc, hd, hmE, hmF]

/-- The positive gap above a simple global bottom is the smaller of the
sector gap and the separation of the two sector bottoms. -/
theorem global_hasGapAboveGround_of_lt
    (c : ParityGroundCertificate A even E) (d : ParityGroundCertificate A (!even) F)
    (hEF : E < F) : HasGapAboveGround A E := by
  refine ⟨min c.gap (F - E), lt_min c.gap_pos (sub_pos.mpr hEF), ?_⟩
  intro u hu
  have hb := c.global_complement_lower_bound_min hP d u
    (hu (c.vector : L2Space) c.vector_mem_parityEigenspace.1)
  have hid : E + min c.gap (F - E) = min (E + c.gap) F := by
    rw [← min_add_add_left]
    congr 1
    ring
  simpa only [hid] using hb

/-- At a crossing the full two-dimensional ground eigenspace is still
isolated; its gap is at least the smaller sector gap. -/
theorem global_hasGapAboveGround_at_crossing
    (c : ParityGroundCertificate A even E) (d : ParityGroundCertificate A (!even) E) :
    HasGapAboveGround A E := by
  refine ⟨min c.gap d.gap, lt_min c.gap_pos d.gap_pos, ?_⟩
  intro u hu
  have hb := c.global_twoMode_complement_lower_bound hP d u
    (hu (c.vector : L2Space) c.vector_mem_parityEigenspace.1)
    (hu (d.vector : L2Space) d.vector_mem_parityEigenspace.1)
  simpa only [min_add_add_left] using hb

end ParityGroundCertificate
end InfiniteZero
